// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzF7XEVorCbHVWjIH-iHPBmSKN_S5u_SY',
    appId: '1:61869919484:web:8368ae3399291251011b79',
    messagingSenderId: '61869919484',
    projectId: 'kpa-erp-system-41c3a',
    authDomain: 'kpa-erp-system-41c3a.firebaseapp.com',
    storageBucket: 'kpa-erp-system-41c3a.firebasestorage.app',
    measurementId: 'G-EJCRPEDYQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDphrzvxLFT8jBHC1JxtzM-ow2W7z_qE9k',
    appId: '1:61869919484:android:21a401f13e5010be011b79',
    messagingSenderId: '61869919484',
    projectId: 'kpa-erp-system-41c3a',
    storageBucket: 'kpa-erp-system-41c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhIIy04xqYCc76IgiAdsuj2Wv9tJqyryA',
    appId: '1:61869919484:ios:e889060f5f7d2e79011b79',
    messagingSenderId: '61869919484',
    projectId: 'kpa-erp-system-41c3a',
    storageBucket: 'kpa-erp-system-41c3a.firebasestorage.app',
    iosBundleId: 'com.example.kpaErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzF7XEVorCbHVWjIH-iHPBmSKN_S5u_SY',
    appId: '1:61869919484:web:6e652c33f533c5eb011b79',
    messagingSenderId: '61869919484',
    projectId: 'kpa-erp-system-41c3a',
    authDomain: 'kpa-erp-system-41c3a.firebaseapp.com',
    storageBucket: 'kpa-erp-system-41c3a.firebasestorage.app',
    measurementId: 'G-0FGRQNE72W',
  );
}
